main: Makefile
	pdflatex resume_Saurav_Ghosh
	pdflatex resume_Saurav_Ghosh
	bibtex resume_Saurav_Ghosh
	pdflatex resume_Saurav_Ghosh
	bibtex resume_Saurav_Ghosh
	pdflatex resume_Saurav_Ghosh
	pdflatex resume_Saurav_Ghosh

clean:
	-rm -rf *.out *.aux *.bbl *.blg *.log *.synctex.gz
	-rm -rf *.dvi *.xml *.bcf

